### PR TITLE
Update pulls_summary.py

### PR DESCRIPTION
**Pull request by JBrame**
Return an array of jsons rather than pre-formatted results for easier processing by the client

### CODE REVIEW

**Comment by JBrame** [comment]
I'm not sure if this has other knock on implications (only tested it with single image), but I think its better to return a dictionary or something rather than pre-formatted results that will need extra logic creating to parse

**Comment by prateekt** [comment]
The original plan was to return a CardPredictionResult since that is a defined structure. I was trying to make your life easier here. We can also implement a toJSON() function in that if you prefer JSON output.

**Comment by JBrame** [comment]
Ah fair enough. Actually my use case is basically that I have a database of cards and I want to be able to analyse bulk images of my cards and confirm it's the one I'm after / look up in a list of ones that I need to auto complete a collection. 

So I need some structure that let's me pick out the name / set / card number separately to check against an input. 

If you already have some other way to get a json result then that's great 👍

**Comment by prateekt** [comment]
@JBrame See if this API change will work for you -- https://github.com/prateekt/pokemon-card-recognizer/pull/11

**Pull request closed without merging**
